steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Run a simple command
    run: echo "Hello from GitHub Actions!"

  - name: Give execute permission to hello.sh
    run: chmod +x hello.sh

  - name: Run shell script
    run: |
      ./hello.sh
      echo "This pipeline runs automatically"
      echo "CI/CD basics learned"

